# Generated by Django 6.0.5 on 2026-06-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_productgallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_percentage',
            field=models.FloatField(default=0),
        ),
    ]
