# Generated by Django 6.0.5 on 2026-06-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('JazzCash', 'JazzCash'), ('EasyPaisa', 'EasyPaisa')], default='COD', max_length=20),
        ),
    ]
