# Generated by Django 6.0.5 on 2026-06-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(default='Sales Tax', max_length=100)),
                ('tax_percentage', models.FloatField(default=2.0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
